name: Build Micromamba env
run-name: ${{ github.actor }} is building mm env

on:
  - workflow_dispatch

jobs:
  build-conda-env:
    runs-on: ubuntu-latest
    steps:
      - name: Test init path
        run: |
          pwd
          echo ${{ github.workspace }}
          ls -al ${{ github.workspace }}

      - name: Checkout conda-env
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout pkg-1
        uses: actions/checkout@v3
        with:
          repository: oscar6echo-gha/pkg-1
          path: pkg-1

      - name: Test path
        run: |
          echo ${{ github.workspace }}
          ls -al ${{ github.workspace }}

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "1.4.4-0"
          environment-file: ${{ github.workspace }}/main/env.yml
          condarc-file: ${{ github.workspace }}/main/.condarc
          create-args: -v
          init-shell: bash
          cache-environment: true
          post-cleanup: "all"

      - name: Test micromamba env
        run: |
          which python
          which pip
          python -c "import polars"
          python -c "import dotenv"
          pytest --version
        shell: bash -l {0}

      - name: Install pkg-1 in env
        run: |
          cd ${{ github.workspace }}/pkg-1
          pip install .
        shell: bash -l {0}

      - name: Test pkg-1
        run: |
          python -c "import pkg_1.example as m; print(m.times_two(3))"
        shell: bash -l {0}

